import { create } from 'zustand'

export interface CustomThemePreview {
  background: string
  text: string
  accent: string
  secondary: string
}

export interface CustomTheme {
  id: string
  name: string
  description: string
  accentColor: string
  previewColors: CustomThemePreview
}

export const CUSTOM_THEMES: CustomTheme[] = [
  {
    id: 'utopia-tokyo',
    name: 'Akai',
    description: 'Bold red accents against a clean monochrome palette',
    accentColor: '#ff1919',
    previewColors: {
      background: '#000000',
      text: '#14171f',
      accent: '#ff1919',
      secondary: '#ebe5ce',
    },
  },
  {
    id: 'sougen',
    name: 'Sumi',
    description: 'Pure black-and-white contrast inspired by Japanese ink',
    accentColor: '#ffffff',
    previewColors: {
      background: '#000000',
      text: '#ffffff',
      accent: '#ffffff',
      secondary: '#e5e7eb',
    },
  },
  {
    id: 'fallen-grape',
    name: 'Copper Vine',
    description: 'Warm earthy tones with copper accents and natural wine vibes',
    accentColor: '#e3a36e',
    previewColors: {
      background: '#e1c6ab',
      text: '#573d21',
      accent: '#e3a36e',
      secondary: '#d8deb7',
    },
  },
  {
    id: 'chainzoku',
    name: 'Zoku',
    description: 'Dark cyber-minimal theme with electric lime accents',
    accentColor: '#cdfb52',
    previewColors: {
      background: '#000000',
      text: '#fffff7',
      accent: '#cdfb52',
      secondary: '#1c1616',
    },
  },
  {
    id: 'branding-agency',
    name: 'Atelier Noir',
    description: 'Premium dark theme with gold accents and teal undertones',
    accentColor: '#bc994e',
    previewColors: {
      background: '#000000',
      text: '#ffffff',
      accent: '#bc994e',
      secondary: '#005368',
    },
  },
  {
    id: 'garden-eight',
    name: 'Eighth Garden',
    description: 'Minimal dark theme with warm cream accents',
    accentColor: '#dbd6d0',
    previewColors: {
      background: '#000000',
      text: '#ffffff',
      accent: '#dbd6d0',
      secondary: '#1e1f1f',
    },
  },
  {
    id: 'unseen-studio',
    name: 'Obscura',
    description: 'Stark black-on-white minimal theme with hidden depths',
    accentColor: '#ffffff',
    previewColors: {
      background: '#000000',
      text: '#ffffff',
      accent: '#ffffff',
      secondary: '#d6d6d6',
    },
  },
  {
    id: 'stark',
    name: 'Viola',
    description: 'Dark theme with deep purple-blue accents',
    accentColor: '#381fd1',
    previewColors: {
      background: '#000000',
      text: '#f6f6eb',
      accent: '#381fd1',
      secondary: '#10284b',
    },
  },
]

// ── Theme color variable maps ──────────────────────────────────────────────
// These are set as inline styles on <html> to bypass CSS cascade layer issues.
type ThemeVars = Record<string, string>
type ThemePalette = {
  dark: ThemeVars
  light: ThemeVars
}

const DEFAULT_PALETTE: ThemePalette = {
  dark: {
    '--color-on-background': '#e5e2e1',
    '--color-on-tertiary': '#233143',
    '--color-on-surface-variant': '#bec7d4',
    '--color-secondary-fixed-dim': '#d0bcff',
    '--color-surface-tint': '#98cbff',
    '--color-on-error': '#690005',
    '--color-on-primary-fixed': '#001d33',
    '--color-surface-container-high': '#2a2a2a',
    '--color-tertiary-container': '#8f9eb3',
    '--color-surface-bright': '#3a3939',
    '--color-inverse-surface': '#e5e2e1',
    '--color-on-secondary-fixed': '#23005c',
    '--color-secondary-fixed': '#e9ddff',
    '--color-primary-fixed-dim': '#98cbff',
    '--color-inverse-primary': '#00629d',
    '--color-on-tertiary-fixed-variant': '#39485a',
    '--color-surface-container-lowest': '#0e0e0e',
    '--color-secondary': '#d0bcff',
    '--color-primary-fixed': '#cfe5ff',
    '--color-on-surface': '#e5e2e1',
    '--color-on-error-container': '#ffdad6',
    '--color-error': '#ffb4ab',
    '--color-outline-variant': '#3f4852',
    '--color-on-primary': '#003354',
    '--color-on-primary-container': '#00375a',
    '--color-surface-variant': '#353534',
    '--color-on-secondary': '#3c0091',
    '--color-tertiary-fixed': '#d4e4fa',
    '--color-surface-dim': '#131313',
    '--color-tertiary-fixed-dim': '#b9c8de',
    '--color-on-tertiary-container': '#273547',
    '--color-surface-container-highest': '#353534',
    '--color-primary': '#98cbff',
    '--color-inverse-on-surface': '#313030',
    '--color-surface-container-low': '#1c1b1b',
    '--color-error-container': '#93000a',
    '--color-surface-container': '#201f1f',
    '--color-tertiary': '#b9c8de',
    '--color-primary-container': '#00a3ff',
    '--color-background': '#131313',
    '--color-on-secondary-fixed-variant': '#5516be',
    '--color-secondary-container': '#571bc1',
    '--color-on-tertiary-fixed': '#0d1c2d',
    '--color-on-primary-fixed-variant': '#004a77',
    '--color-on-secondary-container': '#c4abff',
    '--color-surface': '#131313',
    '--color-outline': '#88919d',
  },
  light: {
    '--color-on-background': '#1c1b1b',
    '--color-on-surface': '#1c1b1b',
    '--color-on-surface-variant': '#49454f',
    '--color-surface': '#f5f0eb',
    '--color-surface-dim': '#e8e0d8',
    '--color-surface-bright': '#fff8f0',
    '--color-surface-container': '#efe7df',
    '--color-surface-container-high': '#e8ddd2',
    '--color-surface-container-highest': '#e0d4c6',
    '--color-surface-container-low': '#f5efe9',
    '--color-surface-container-lowest': '#ffffff',
    '--color-background': '#faf5eb',
    '--color-outline': '#79747e',
    '--color-outline-variant': '#cac4d0',
    '--color-primary': '#98cbff',
    '--color-on-primary': '#003354',
    '--color-primary-container': '#cfe5ff',
    '--color-on-primary-container': '#001d33',
    '--color-secondary': '#1c1b1b',
    '--color-on-secondary': '#ffffff',
    '--color-secondary-container': '#e0d4c6',
    '--color-on-secondary-container': '#1c1b1b',
    '--color-error': '#ba1a1a',
    '--color-on-error': '#ffffff',
    '--color-error-container': '#ffdad6',
    '--color-on-error-container': '#410002',
    '--color-inverse-surface': '#313030',
    '--color-inverse-on-surface': '#f5f0eb',
    '--color-inverse-primary': '#98cbff',
    '--color-surface-tint': '#98cbff',
    '--color-primary-fixed': '#cfe5ff',
    '--color-primary-fixed-dim': '#98cbff',
    '--color-on-primary-fixed': '#001d33',
    '--color-on-primary-fixed-variant': '#004a77',
    '--color-secondary-fixed': '#1c1b1b',
    '--color-secondary-fixed-dim': '#3a3a3a',
    '--color-on-secondary-fixed': '#23005c',
    '--color-on-secondary-fixed-variant': '#5516be',
    '--color-tertiary': '#b9c8de',
    '--color-tertiary-container': '#d4e4fa',
    '--color-on-tertiary': '#233143',
    '--color-on-tertiary-container': '#273547',
    '--color-tertiary-fixed': '#d4e4fa',
    '--color-tertiary-fixed-dim': '#b9c8de',
    '--color-on-tertiary-fixed': '#0d1c2d',
    '--color-on-tertiary-fixed-variant': '#39485a',
    '--color-surface-variant': '#e8e0d8',
  },
}

const THEME_PALETTES: Record<string, ThemePalette> = {
  'utopia-tokyo': {
    dark: {
      '--color-on-background': '#ebe5ce',
      '--color-on-surface': '#ebe5ce',
      '--color-on-surface-variant': '#9a9a9a',
      '--color-surface': '#0d0d0d',
      '--color-surface-dim': '#080808',
      '--color-surface-bright': '#1a1a1a',
      '--color-surface-container': '#111111',
      '--color-surface-container-high': '#1a1a1a',
      '--color-surface-container-highest': '#222222',
      '--color-surface-container-low': '#0f0f0f',
      '--color-surface-container-lowest': '#050505',
      '--color-background': '#000000',
      '--color-outline': '#3a3a3a',
      '--color-outline-variant': '#2a2a2a',
      '--color-primary': '#ff1919',
      '--color-on-primary': '#ffffff',
      '--color-primary-container': '#ff1919',
      '--color-on-primary-container': '#ffffff',
      '--color-secondary': '#ebe5ce',
      '--color-on-secondary': '#14171f',
      '--color-secondary-container': '#2a2a2a',
      '--color-on-secondary-container': '#ebe5ce',
      '--color-error': '#ff1919',
      '--color-on-error': '#ffffff',
      '--color-error-container': '#3a0000',
      '--color-on-error-container': '#ffb4ab',
      '--color-inverse-surface': '#ebe5ce',
      '--color-inverse-on-surface': '#14171f',
      '--color-inverse-primary': '#14171f',
      '--color-surface-tint': '#ff1919',
      '--color-primary-fixed': '#ff1919',
      '--color-primary-fixed-dim': '#cc0000',
      '--color-on-primary-fixed': '#ffffff',
      '--color-on-primary-fixed-variant': '#ffffff',
      '--color-secondary-fixed': '#ebe5ce',
      '--color-secondary-fixed-dim': '#d0cbb8',
      '--color-on-secondary-fixed': '#14171f',
      '--color-on-secondary-fixed-variant': '#14171f',
      '--color-tertiary': '#ebe5ce',
      '--color-tertiary-container': '#2a2a2a',
      '--color-on-tertiary': '#14171f',
      '--color-on-tertiary-container': '#ebe5ce',
      '--color-tertiary-fixed': '#ebe5ce',
      '--color-tertiary-fixed-dim': '#d0cbb8',
      '--color-on-tertiary-fixed': '#14171f',
      '--color-on-tertiary-fixed-variant': '#14171f',
      '--color-surface-variant': '#2a2a2a',
    },
    light: {
      '--color-on-background': '#2c2c2c',
      '--color-on-surface': '#2c2c2c',
      '--color-on-surface-variant': '#6a6a6a',
      '--color-surface': '#f5f0eb',
      '--color-surface-dim': '#e8e0d8',
      '--color-surface-bright': '#fff8f0',
      '--color-surface-container': '#efe7df',
      '--color-surface-container-high': '#e8ddd2',
      '--color-surface-container-highest': '#e0d4c6',
      '--color-surface-container-low': '#f5efe9',
      '--color-surface-container-lowest': '#ffffff',
      '--color-background': '#faf5eb',
      '--color-outline': '#c0bcb4',
      '--color-outline-variant': '#d4d0c8',
      '--color-primary': '#d41010',
      '--color-on-primary': '#ffffff',
      '--color-primary-container': '#ff4a4a',
      '--color-on-primary-container': '#2e0000',
      '--color-secondary': '#2c2c2c',
      '--color-on-secondary': '#ffffff',
      '--color-secondary-container': '#e0d4c6',
      '--color-on-secondary-container': '#2c2c2c',
      '--color-error': '#ba1a1a',
      '--color-on-error': '#ffffff',
      '--color-error-container': '#ffdad6',
      '--color-on-error-container': '#410002',
      '--color-inverse-surface': '#2c2c2c',
      '--color-inverse-on-surface': '#f5f0eb',
      '--color-inverse-primary': '#ff1919',
      '--color-surface-tint': '#ff1919',
      '--color-primary-fixed': '#d41010',
      '--color-primary-fixed-dim': '#a80000',
      '--color-on-primary-fixed': '#ffffff',
      '--color-on-primary-fixed-variant': '#ffffff',
      '--color-secondary-fixed': '#2c2c2c',
      '--color-secondary-fixed-dim': '#3a3a3a',
      '--color-on-secondary-fixed': '#ffffff',
      '--color-on-secondary-fixed-variant': '#ffffff',
      '--color-tertiary': '#2c2c2c',
      '--color-tertiary-container': '#e0d4c6',
      '--color-on-tertiary': '#ffffff',
      '--color-on-tertiary-container': '#2c2c2c',
      '--color-tertiary-fixed': '#2c2c2c',
      '--color-tertiary-fixed-dim': '#3a3a3a',
      '--color-on-tertiary-fixed': '#ffffff',
      '--color-on-tertiary-fixed-variant': '#ffffff',
      '--color-surface-variant': '#e8e0d8',
    },
  },
  'sougen': {
    dark: {
      '--color-on-background': '#ffffff',
      '--color-on-surface': '#ffffff',
      '--color-on-surface-variant': '#a0a0a0',
      '--color-surface': '#0a0a0a',
      '--color-surface-dim': '#060606',
      '--color-surface-bright': '#1a1a1a',
      '--color-surface-container': '#0e0e0e',
      '--color-surface-container-high': '#161616',
      '--color-surface-container-highest': '#1e1e1e',
      '--color-surface-container-low': '#0c0c0c',
      '--color-surface-container-lowest': '#030303',
      '--color-background': '#000000',
      '--color-outline': '#e5e7eb',
      '--color-outline-variant': '#3a3a3a',
      '--color-primary': '#ffffff',
      '--color-on-primary': '#000000',
      '--color-primary-container': '#ffffff',
      '--color-on-primary-container': '#000000',
      '--color-secondary': '#e5e7eb',
      '--color-on-secondary': '#000000',
      '--color-secondary-container': '#2a2a2a',
      '--color-on-secondary-container': '#e5e7eb',
      '--color-error': '#ff6b6b',
      '--color-on-error': '#000000',
      '--color-error-container': '#3a1515',
      '--color-on-error-container': '#ffb4ab',
      '--color-inverse-surface': '#ffffff',
      '--color-inverse-on-surface': '#000000',
      '--color-inverse-primary': '#000000',
      '--color-surface-tint': '#ffffff',
      '--color-primary-fixed': '#ffffff',
      '--color-primary-fixed-dim': '#d0d0d0',
      '--color-on-primary-fixed': '#000000',
      '--color-on-primary-fixed-variant': '#000000',
      '--color-secondary-fixed': '#e5e7eb',
      '--color-secondary-fixed-dim': '#c0c2c8',
      '--color-on-secondary-fixed': '#000000',
      '--color-on-secondary-fixed-variant': '#000000',
      '--color-tertiary': '#e5e7eb',
      '--color-tertiary-container': '#2a2a2a',
      '--color-on-tertiary': '#000000',
      '--color-on-tertiary-container': '#e5e7eb',
      '--color-tertiary-fixed': '#e5e7eb',
      '--color-tertiary-fixed-dim': '#c0c2c8',
      '--color-on-tertiary-fixed': '#000000',
      '--color-on-tertiary-fixed-variant': '#000000',
      '--color-surface-variant': '#2a2a2a',
    },
    light: {
      '--color-on-background': '#1a1a1a',
      '--color-on-surface': '#1a1a1a',
      '--color-on-surface-variant': '#6a6a6a',
      '--color-surface': '#f0eee8',
      '--color-surface-dim': '#e4e2dc',
      '--color-surface-bright': '#faf8f2',
      '--color-surface-container': '#ece8e2',
      '--color-surface-container-high': '#e4e2dc',
      '--color-surface-container-highest': '#dcdad4',
      '--color-surface-container-low': '#f4f2ec',
      '--color-surface-container-lowest': '#fcfaf4',
      '--color-background': '#f7f5f0',
      '--color-outline': '#b0b0b0',
      '--color-outline-variant': '#d0cec8',
      '--color-primary': '#1a1a1a',
      '--color-on-primary': '#ffffff',
      '--color-primary-container': '#1a1a1a',
      '--color-on-primary-container': '#ffffff',
      '--color-secondary': '#1a1a1a',
      '--color-on-secondary': '#ffffff',
      '--color-secondary-container': '#dcdad4',
      '--color-on-secondary-container': '#1a1a1a',
      '--color-error': '#ba1a1a',
      '--color-on-error': '#ffffff',
      '--color-error-container': '#ffdad6',
      '--color-on-error-container': '#410002',
      '--color-inverse-surface': '#1a1a1a',
      '--color-inverse-on-surface': '#f7f5f0',
      '--color-inverse-primary': '#d0cec8',
      '--color-surface-tint': '#1a1a1a',
      '--color-primary-fixed': '#1a1a1a',
      '--color-primary-fixed-dim': '#4a4a4a',
      '--color-on-primary-fixed': '#ffffff',
      '--color-on-primary-fixed-variant': '#1a1a1a',
      '--color-secondary-fixed': '#1a1a1a',
      '--color-secondary-fixed-dim': '#4a4a4a',
      '--color-on-secondary-fixed': '#ffffff',
      '--color-on-secondary-fixed-variant': '#1a1a1a',
      '--color-tertiary': '#1a1a1a',
      '--color-tertiary-container': '#dcdad4',
      '--color-on-tertiary': '#ffffff',
      '--color-on-tertiary-container': '#1a1a1a',
      '--color-tertiary-fixed': '#1a1a1a',
      '--color-tertiary-fixed-dim': '#4a4a4a',
      '--color-on-tertiary-fixed': '#ffffff',
      '--color-on-tertiary-fixed-variant': '#1a1a1a',
      '--color-surface-variant': '#e8e6e0',
    },
  },
  'fallen-grape': {
    dark: {
      '--color-on-background': '#e1c6ab',
      '--color-on-surface': '#e1c6ab',
      '--color-on-surface-variant': '#a09080',
      '--color-surface': '#221c16',
      '--color-surface-dim': '#1a1410',
      '--color-surface-bright': '#2e2822',
      '--color-surface-container': '#241e18',
      '--color-surface-container-high': '#2e2822',
      '--color-surface-container-highest': '#38322c',
      '--color-surface-container-low': '#221c16',
      '--color-surface-container-lowest': '#140e0a',
      '--color-background': '#1a1410',
      '--color-outline': '#5a4a3a',
      '--color-outline-variant': '#3a2e24',
      '--color-primary': '#e3a36e',
      '--color-on-primary': '#ffffff',
      '--color-primary-container': '#e3a36e',
      '--color-on-primary-container': '#ffffff',
      '--color-secondary': '#d8deb7',
      '--color-on-secondary': '#1a1410',
      '--color-secondary-container': '#3a3420',
      '--color-on-secondary-container': '#d8deb7',
      '--color-error': '#ffb4ab',
      '--color-on-error': '#690005',
      '--color-error-container': '#93000a',
      '--color-on-error-container': '#ffdad6',
      '--color-inverse-surface': '#e1c6ab',
      '--color-inverse-on-surface': '#1a1410',
      '--color-inverse-primary': '#e3a36e',
      '--color-surface-tint': '#e3a36e',
      '--color-primary-fixed': '#e3a36e',
      '--color-primary-fixed-dim': '#c8895c',
      '--color-on-primary-fixed': '#ffffff',
      '--color-on-primary-fixed-variant': '#ffffff',
      '--color-secondary-fixed': '#d8deb7',
      '--color-secondary-fixed-dim': '#a0a88a',
      '--color-on-secondary-fixed': '#1a1410',
      '--color-on-secondary-fixed-variant': '#1a1410',
      '--color-tertiary': '#e1c6ab',
      '--color-tertiary-container': '#3a2e24',
      '--color-on-tertiary': '#1a1410',
      '--color-on-tertiary-container': '#e1c6ab',
      '--color-tertiary-fixed': '#e1c6ab',
      '--color-tertiary-fixed-dim': '#c0a88e',
      '--color-on-tertiary-fixed': '#1a1410',
      '--color-on-tertiary-fixed-variant': '#1a1410',
      '--color-surface-variant': '#3a2e24',
    },
    light: {
      '--color-on-background': '#2e2218',
      '--color-on-surface': '#2e2218',
      '--color-on-surface-variant': '#7a6b5e',
      '--color-surface': '#f5ede4',
      '--color-surface-dim': '#e8ddd2',
      '--color-surface-bright': '#fdf5ec',
      '--color-surface-container': '#efe3d8',
      '--color-surface-container-high': '#e8ddd2',
      '--color-surface-container-highest': '#e0d2c5',
      '--color-surface-container-low': '#f5efe9',
      '--color-surface-container-lowest': '#ffffff',
      '--color-background': '#faf2e8',
      '--color-outline': '#b8a898',
      '--color-outline-variant': '#d4c8b8',
      '--color-primary': '#c88050',
      '--color-on-primary': '#ffffff',
      '--color-primary-container': '#e3a36e',
      '--color-on-primary-container': '#2e2218',
      '--color-secondary': '#2e2218',
      '--color-on-secondary': '#ffffff',
      '--color-secondary-container': '#e0d2c5',
      '--color-on-secondary-container': '#2e2218',
      '--color-error': '#ba1a1a',
      '--color-on-error': '#ffffff',
      '--color-error-container': '#ffdad6',
      '--color-on-error-container': '#410002',
      '--color-inverse-surface': '#2e2218',
      '--color-inverse-on-surface': '#f5ede4',
      '--color-inverse-primary': '#e3a36e',
      '--color-surface-tint': '#e3a36e',
      '--color-primary-fixed': '#e3a36e',
      '--color-primary-fixed-dim': '#c88050',
      '--color-on-primary-fixed': '#2e2218',
      '--color-on-primary-fixed-variant': '#2e2218',
      '--color-secondary-fixed': '#2e2218',
      '--color-secondary-fixed-dim': '#4a3a2c',
      '--color-on-secondary-fixed': '#ffffff',
      '--color-on-secondary-fixed-variant': '#ffffff',
      '--color-tertiary': '#2e2218',
      '--color-tertiary-container': '#e0d2c5',
      '--color-on-tertiary': '#ffffff',
      '--color-on-tertiary-container': '#2e2218',
      '--color-tertiary-fixed': '#2e2218',
      '--color-tertiary-fixed-dim': '#4a3a2c',
      '--color-on-tertiary-fixed': '#ffffff',
      '--color-on-tertiary-fixed-variant': '#ffffff',
      '--color-surface-variant': '#e8dcd0',
    },
  },
  'chainzoku': {
    dark: {
      '--color-on-background': '#fffff7',
      '--color-on-surface': '#fffff7',
      '--color-on-surface-variant': '#8a8a80',
      '--color-surface': '#1c1616',
      '--color-surface-dim': '#0e0a0a',
      '--color-surface-bright': '#2a2424',
      '--color-surface-container': '#201a1a',
      '--color-surface-container-high': '#282222',
      '--color-surface-container-highest': '#322c2c',
      '--color-surface-container-low': '#1c1616',
      '--color-surface-container-lowest': '#080505',
      '--color-background': '#000000',
      '--color-outline': '#3a3a3a',
      '--color-outline-variant': '#2a2a2a',
      '--color-primary': '#cdfb52',
      '--color-on-primary': '#000000',
      '--color-primary-container': '#cdfb52',
      '--color-on-primary-container': '#000000',
      '--color-secondary': '#fffff7',
      '--color-on-secondary': '#1c1616',
      '--color-secondary-container': '#3a3a3a',
      '--color-on-secondary-container': '#fffff7',
      '--color-error': '#ff6b6b',
      '--color-on-error': '#000000',
      '--color-error-container': '#3a1515',
      '--color-on-error-container': '#ffb4ab',
      '--color-inverse-surface': '#fffff7',
      '--color-inverse-on-surface': '#1c1616',
      '--color-inverse-primary': '#1c1616',
      '--color-surface-tint': '#cdfb52',
      '--color-primary-fixed': '#cdfb52',
      '--color-primary-fixed-dim': '#a8d43a',
      '--color-on-primary-fixed': '#000000',
      '--color-on-primary-fixed-variant': '#000000',
      '--color-secondary-fixed': '#fffff7',
      '--color-secondary-fixed-dim': '#d0d0c8',
      '--color-on-secondary-fixed': '#1c1616',
      '--color-on-secondary-fixed-variant': '#1c1616',
      '--color-tertiary': '#fffff7',
      '--color-tertiary-container': '#3a3a3a',
      '--color-on-tertiary': '#1c1616',
      '--color-on-tertiary-container': '#fffff7',
      '--color-tertiary-fixed': '#fffff7',
      '--color-tertiary-fixed-dim': '#d0d0c8',
      '--color-on-tertiary-fixed': '#1c1616',
      '--color-on-tertiary-fixed-variant': '#1c1616',
      '--color-surface-variant': '#3a3a3a',
    },
    light: {
      '--color-on-background': '#1c1616',
      '--color-on-surface': '#1c1616',
      '--color-on-surface-variant': '#5a5a50',
      '--color-surface': '#f0ebe5',
      '--color-surface-dim': '#e4ddd7',
      '--color-surface-bright': '#fcf7f1',
      '--color-surface-container': '#ece5df',
      '--color-surface-container-high': '#e4ddd7',
      '--color-surface-container-highest': '#dcd5cf',
      '--color-surface-container-low': '#f4efe9',
      '--color-surface-container-lowest': '#ffffff',
      '--color-background': '#f5f0eb',
      '--color-outline': '#8a8a80',
      '--color-outline-variant': '#c5c0ba',
      '--color-primary': '#a0d838',
      '--color-on-primary': '#000000',
      '--color-primary-container': '#cdfb52',
      '--color-on-primary-container': '#000000',
      '--color-secondary': '#1c1616',
      '--color-on-secondary': '#ffffff',
      '--color-secondary-container': '#dcd5cf',
      '--color-on-secondary-container': '#1c1616',
      '--color-error': '#ba1a1a',
      '--color-on-error': '#ffffff',
      '--color-error-container': '#ffdad6',
      '--color-on-error-container': '#410002',
      '--color-inverse-surface': '#1c1616',
      '--color-inverse-on-surface': '#f0ebe5',
      '--color-inverse-primary': '#cdfb52',
      '--color-surface-tint': '#cdfb52',
      '--color-primary-fixed': '#cdfb52',
      '--color-primary-fixed-dim': '#a8d43a',
      '--color-on-primary-fixed': '#000000',
      '--color-on-primary-fixed-variant': '#000000',
      '--color-secondary-fixed': '#1c1616',
      '--color-secondary-fixed-dim': '#3a3a3a',
      '--color-on-secondary-fixed': '#ffffff',
      '--color-on-secondary-fixed-variant': '#ffffff',
      '--color-tertiary': '#1c1616',
      '--color-tertiary-container': '#dcd5cf',
      '--color-on-tertiary': '#ffffff',
      '--color-on-tertiary-container': '#1c1616',
      '--color-tertiary-fixed': '#1c1616',
      '--color-tertiary-fixed-dim': '#3a3a3a',
      '--color-on-tertiary-fixed': '#ffffff',
      '--color-on-tertiary-fixed-variant': '#ffffff',
      '--color-surface-variant': '#e4ddd7',
    },
  },
  'branding-agency': {
    dark: {
      '--color-on-background': '#ffffff',
      '--color-on-surface': '#ffffff',
      '--color-on-surface-variant': '#d4d4d4',
      '--color-surface': '#0a0a0a',
      '--color-surface-dim': '#060606',
      '--color-surface-bright': '#1a1a1a',
      '--color-surface-container': '#0e0e0e',
      '--color-surface-container-high': '#161616',
      '--color-surface-container-highest': '#1e1e1e',
      '--color-surface-container-low': '#0c0c0c',
      '--color-surface-container-lowest': '#030303',
      '--color-background': '#000000',
      '--color-outline': '#005368',
      '--color-outline-variant': '#003a47',
      '--color-primary': '#bc994e',
      '--color-on-primary': '#000000',
      '--color-primary-container': '#bc994e',
      '--color-on-primary-container': '#000000',
      '--color-secondary': '#a3fffe',
      '--color-on-secondary': '#000000',
      '--color-secondary-container': '#004d4d',
      '--color-on-secondary-container': '#a3fffe',
      '--color-error': '#ff6b6b',
      '--color-on-error': '#000000',
      '--color-error-container': '#3a1515',
      '--color-on-error-container': '#ffb4ab',
      '--color-inverse-surface': '#ffffff',
      '--color-inverse-on-surface': '#000000',
      '--color-inverse-primary': '#000000',
      '--color-surface-tint': '#bc994e',
      '--color-primary-fixed': '#bc994e',
      '--color-primary-fixed-dim': '#9a7d3c',
      '--color-on-primary-fixed': '#000000',
      '--color-on-primary-fixed-variant': '#000000',
      '--color-secondary-fixed': '#a3fffe',
      '--color-secondary-fixed-dim': '#80d0cf',
      '--color-on-secondary-fixed': '#000000',
      '--color-on-secondary-fixed-variant': '#000000',
      '--color-tertiary': '#d4d4d4',
      '--color-tertiary-container': '#2a2a2a',
      '--color-on-tertiary': '#000000',
      '--color-on-tertiary-container': '#d4d4d4',
      '--color-tertiary-fixed': '#d4d4d4',
      '--color-tertiary-fixed-dim': '#b0b0b0',
      '--color-on-tertiary-fixed': '#000000',
      '--color-on-tertiary-fixed-variant': '#000000',
      '--color-surface-variant': '#2a2a2a',
    },
    light: {
      '--color-on-background': '#1a1a1a',
      '--color-on-surface': '#1a1a1a',
      '--color-on-surface-variant': '#606060',
      '--color-surface': '#f3ede3',
      '--color-surface-dim': '#e7e0d6',
      '--color-surface-bright': '#fbf5eb',
      '--color-surface-container': '#efe8de',
      '--color-surface-container-high': '#e7e0d6',
      '--color-surface-container-highest': '#dfd8ce',
      '--color-surface-container-low': '#f7f0e6',
      '--color-surface-container-lowest': '#ffffff',
      '--color-background': '#f5f0e8',
      '--color-outline': '#8a8070',
      '--color-outline-variant': '#c5bcaa',
      '--color-primary': '#bc994e',
      '--color-on-primary': '#000000',
      '--color-primary-container': '#bc994e',
      '--color-on-primary-container': '#000000',
      '--color-secondary': '#1a1a1a',
      '--color-on-secondary': '#ffffff',
      '--color-secondary-container': '#dfd8ce',
      '--color-on-secondary-container': '#1a1a1a',
      '--color-error': '#ba1a1a',
      '--color-on-error': '#ffffff',
      '--color-error-container': '#ffdad6',
      '--color-on-error-container': '#410002',
      '--color-inverse-surface': '#1a1a1a',
      '--color-inverse-on-surface': '#f3ede3',
      '--color-inverse-primary': '#bc994e',
      '--color-surface-tint': '#bc994e',
      '--color-primary-fixed': '#bc994e',
      '--color-primary-fixed-dim': '#9a7d3c',
      '--color-on-primary-fixed': '#000000',
      '--color-on-primary-fixed-variant': '#000000',
      '--color-secondary-fixed': '#1a1a1a',
      '--color-secondary-fixed-dim': '#3a3a3a',
      '--color-on-secondary-fixed': '#ffffff',
      '--color-on-secondary-fixed-variant': '#ffffff',
      '--color-tertiary': '#1a1a1a',
      '--color-tertiary-container': '#dfd8ce',
      '--color-on-tertiary': '#ffffff',
      '--color-on-tertiary-container': '#1a1a1a',
      '--color-tertiary-fixed': '#1a1a1a',
      '--color-tertiary-fixed-dim': '#3a3a3a',
      '--color-on-tertiary-fixed': '#ffffff',
      '--color-on-tertiary-fixed-variant': '#ffffff',
      '--color-surface-variant': '#e7e0d6',
    },
  },
  'garden-eight': {
    dark: {
      '--color-on-background': '#ffffff',
      '--color-on-surface': '#ffffff',
      '--color-on-surface-variant': '#dbd6d0',
      '--color-surface': '#0a0a0a',
      '--color-surface-dim': '#060606',
      '--color-surface-bright': '#1a1a1a',
      '--color-surface-container': '#0e0e0e',
      '--color-surface-container-high': '#161616',
      '--color-surface-container-highest': '#1e1e1e',
      '--color-surface-container-low': '#0c0c0c',
      '--color-surface-container-lowest': '#030303',
      '--color-background': '#000000',
      '--color-outline': '#1e1f1f',
      '--color-outline-variant': '#2a2a2a',
      '--color-primary': '#dbd6d0',
      '--color-on-primary': '#000000',
      '--color-primary-container': '#dbd6d0',
      '--color-on-primary-container': '#000000',
      '--color-secondary': '#dbd6d0',
      '--color-on-secondary': '#000000',
      '--color-secondary-container': '#2a2a2a',
      '--color-on-secondary-container': '#dbd6d0',
      '--color-error': '#ff6b6b',
      '--color-on-error': '#000000',
      '--color-error-container': '#3a1515',
      '--color-on-error-container': '#ffb4ab',
      '--color-inverse-surface': '#ffffff',
      '--color-inverse-on-surface': '#000000',
      '--color-inverse-primary': '#000000',
      '--color-surface-tint': '#dbd6d0',
      '--color-primary-fixed': '#dbd6d0',
      '--color-primary-fixed-dim': '#b8b4ae',
      '--color-on-primary-fixed': '#000000',
      '--color-on-primary-fixed-variant': '#000000',
      '--color-secondary-fixed': '#dbd6d0',
      '--color-secondary-fixed-dim': '#b8b4ae',
      '--color-on-secondary-fixed': '#000000',
      '--color-on-secondary-fixed-variant': '#000000',
      '--color-tertiary': '#dbd6d0',
      '--color-tertiary-container': '#2a2a2a',
      '--color-on-tertiary': '#000000',
      '--color-on-tertiary-container': '#dbd6d0',
      '--color-tertiary-fixed': '#dbd6d0',
      '--color-tertiary-fixed-dim': '#b8b4ae',
      '--color-on-tertiary-fixed': '#000000',
      '--color-on-tertiary-fixed-variant': '#000000',
      '--color-surface-variant': '#2a2a2a',
    },
    light: {
      '--color-on-background': '#1a1a1a',
      '--color-on-surface': '#1a1a1a',
      '--color-on-surface-variant': '#6a6a6a',
      '--color-surface': '#f3ede7',
      '--color-surface-dim': '#e7e0da',
      '--color-surface-bright': '#fbf5ef',
      '--color-surface-container': '#efe8e2',
      '--color-surface-container-high': '#e7e0da',
      '--color-surface-container-highest': '#dfd8d2',
      '--color-surface-container-low': '#f7f0ea',
      '--color-surface-container-lowest': '#ffffff',
      '--color-background': '#faf5eb',
      '--color-outline': '#8a8a8a',
      '--color-outline-variant': '#c5c0ba',
      '--color-primary': '#b8b4ae',
      '--color-on-primary': '#000000',
      '--color-primary-container': '#dbd6d0',
      '--color-on-primary-container': '#000000',
      '--color-secondary': '#1a1a1a',
      '--color-on-secondary': '#ffffff',
      '--color-secondary-container': '#dfd8d2',
      '--color-on-secondary-container': '#1a1a1a',
      '--color-error': '#ba1a1a',
      '--color-on-error': '#ffffff',
      '--color-error-container': '#ffdad6',
      '--color-on-error-container': '#410002',
      '--color-inverse-surface': '#1a1a1a',
      '--color-inverse-on-surface': '#f3ede7',
      '--color-inverse-primary': '#dbd6d0',
      '--color-surface-tint': '#dbd6d0',
      '--color-primary-fixed': '#dbd6d0',
      '--color-primary-fixed-dim': '#b8b4ae',
      '--color-on-primary-fixed': '#000000',
      '--color-on-primary-fixed-variant': '#000000',
      '--color-secondary-fixed': '#1a1a1a',
      '--color-secondary-fixed-dim': '#3a3a3a',
      '--color-on-secondary-fixed': '#ffffff',
      '--color-on-secondary-fixed-variant': '#ffffff',
      '--color-tertiary': '#1a1a1a',
      '--color-tertiary-container': '#dfd8d2',
      '--color-on-tertiary': '#ffffff',
      '--color-on-tertiary-container': '#1a1a1a',
      '--color-tertiary-fixed': '#1a1a1a',
      '--color-tertiary-fixed-dim': '#3a3a3a',
      '--color-on-tertiary-fixed': '#ffffff',
      '--color-on-tertiary-fixed-variant': '#ffffff',
      '--color-surface-variant': '#e7e0da',
    },
  },
  'unseen-studio': {
    dark: {
      '--color-on-background': '#ffffff',
      '--color-on-surface': '#ffffff',
      '--color-on-surface-variant': '#d6d6d6',
      '--color-surface': '#0a0a0a',
      '--color-surface-dim': '#060606',
      '--color-surface-bright': '#1a1a1a',
      '--color-surface-container': '#0e0e0e',
      '--color-surface-container-high': '#161616',
      '--color-surface-container-highest': '#1e1e1e',
      '--color-surface-container-low': '#0c0c0c',
      '--color-surface-container-lowest': '#030303',
      '--color-background': '#000000',
      '--color-outline': '#212121',
      '--color-outline-variant': '#2a2a2a',
      '--color-primary': '#ffffff',
      '--color-on-primary': '#000000',
      '--color-primary-container': '#ffffff',
      '--color-on-primary-container': '#000000',
      '--color-secondary': '#d6d6d6',
      '--color-on-secondary': '#000000',
      '--color-secondary-container': '#212121',
      '--color-on-secondary-container': '#d6d6d6',
      '--color-error': '#ff6b6b',
      '--color-on-error': '#000000',
      '--color-error-container': '#3a1515',
      '--color-on-error-container': '#ffb4ab',
      '--color-inverse-surface': '#ffffff',
      '--color-inverse-on-surface': '#000000',
      '--color-inverse-primary': '#000000',
      '--color-surface-tint': '#ffffff',
      '--color-primary-fixed': '#ffffff',
      '--color-primary-fixed-dim': '#d0d0d0',
      '--color-on-primary-fixed': '#000000',
      '--color-on-primary-fixed-variant': '#000000',
      '--color-secondary-fixed': '#d6d6d6',
      '--color-secondary-fixed-dim': '#b0b0b0',
      '--color-on-secondary-fixed': '#000000',
      '--color-on-secondary-fixed-variant': '#000000',
      '--color-tertiary': '#d6d6d6',
      '--color-tertiary-container': '#212121',
      '--color-on-tertiary': '#000000',
      '--color-on-tertiary-container': '#d6d6d6',
      '--color-tertiary-fixed': '#d6d6d6',
      '--color-tertiary-fixed-dim': '#b0b0b0',
      '--color-on-tertiary-fixed': '#000000',
      '--color-on-tertiary-fixed-variant': '#000000',
      '--color-surface-variant': '#2a2a2a',
    },
    light: {
      '--color-on-background': '#161616',
      '--color-on-surface': '#161616',
      '--color-on-surface-variant': '#666666',
      '--color-surface': '#efede8',
      '--color-surface-dim': '#e4e2dd',
      '--color-surface-bright': '#f9f7f2',
      '--color-surface-container': '#ebe9e4',
      '--color-surface-container-high': '#e4e2dd',
      '--color-surface-container-highest': '#dcdad5',
      '--color-surface-container-low': '#f3f1ec',
      '--color-surface-container-lowest': '#fbf9f4',
      '--color-background': '#f5f4f0',
      '--color-outline': '#b0b0b0',
      '--color-outline-variant': '#d0ceca',
      '--color-primary': '#161616',
      '--color-on-primary': '#ffffff',
      '--color-primary-container': '#161616',
      '--color-on-primary-container': '#ffffff',
      '--color-secondary': '#161616',
      '--color-on-secondary': '#ffffff',
      '--color-secondary-container': '#dcdad5',
      '--color-on-secondary-container': '#161616',
      '--color-error': '#ba1a1a',
      '--color-on-error': '#ffffff',
      '--color-error-container': '#ffdad6',
      '--color-on-error-container': '#410002',
      '--color-inverse-surface': '#161616',
      '--color-inverse-on-surface': '#f5f4f0',
      '--color-inverse-primary': '#d0ceca',
      '--color-surface-tint': '#161616',
      '--color-primary-fixed': '#161616',
      '--color-primary-fixed-dim': '#4a4a4a',
      '--color-on-primary-fixed': '#ffffff',
      '--color-on-primary-fixed-variant': '#161616',
      '--color-secondary-fixed': '#161616',
      '--color-secondary-fixed-dim': '#4a4a4a',
      '--color-on-secondary-fixed': '#ffffff',
      '--color-on-secondary-fixed-variant': '#161616',
      '--color-tertiary': '#161616',
      '--color-tertiary-container': '#dcdad5',
      '--color-on-tertiary': '#ffffff',
      '--color-on-tertiary-container': '#161616',
      '--color-tertiary-fixed': '#161616',
      '--color-tertiary-fixed-dim': '#4a4a4a',
      '--color-on-tertiary-fixed': '#ffffff',
      '--color-on-tertiary-fixed-variant': '#161616',
      '--color-surface-variant': '#e8e6e1',
    },
  },
  'stark': {
    dark: {
      '--color-on-background': '#f6f6eb',
      '--color-on-surface': '#f6f6eb',
      '--color-on-surface-variant': '#b0b0b0',
      '--color-surface': '#0a0a0a',
      '--color-surface-dim': '#060606',
      '--color-surface-bright': '#1a1a1a',
      '--color-surface-container': '#0e0e0e',
      '--color-surface-container-high': '#161616',
      '--color-surface-container-highest': '#1e1e1e',
      '--color-surface-container-low': '#0c0c0c',
      '--color-surface-container-lowest': '#030303',
      '--color-background': '#000000',
      '--color-outline': '#e5e7eb',
      '--color-outline-variant': '#3a3a3a',
      '--color-primary': '#6d4aff',
      '--color-on-primary': '#ffffff',
      '--color-primary-container': '#6d4aff',
      '--color-on-primary-container': '#ffffff',
      '--color-secondary': '#f6f6eb',
      '--color-on-secondary': '#000000',
      '--color-secondary-container': '#10284b',
      '--color-on-secondary-container': '#f6f6eb',
      '--color-error': '#ff6b6b',
      '--color-on-error': '#000000',
      '--color-error-container': '#3a1515',
      '--color-on-error-container': '#ffb4ab',
      '--color-inverse-surface': '#f6f6eb',
      '--color-inverse-on-surface': '#000000',
      '--color-inverse-primary': '#10284b',
      '--color-surface-tint': '#6d4aff',
      '--color-primary-fixed': '#6d4aff',
      '--color-primary-fixed-dim': '#381fd1',
      '--color-on-primary-fixed': '#ffffff',
      '--color-on-primary-fixed-variant': '#ffffff',
      '--color-secondary-fixed': '#f6f6eb',
      '--color-secondary-fixed-dim': '#d0d0c8',
      '--color-on-secondary-fixed': '#000000',
      '--color-on-secondary-fixed-variant': '#000000',
      '--color-tertiary': '#f6f6eb',
      '--color-tertiary-container': '#10284b',
      '--color-on-tertiary': '#000000',
      '--color-on-tertiary-container': '#f6f6eb',
      '--color-tertiary-fixed': '#f6f6eb',
      '--color-tertiary-fixed-dim': '#d0d0c8',
      '--color-on-tertiary-fixed': '#000000',
      '--color-on-tertiary-fixed-variant': '#000000',
      '--color-surface-variant': '#2a2a2a',
    },
    light: {
      '--color-on-background': '#1c1b1b',
      '--color-on-surface': '#1c1b1b',
      '--color-on-surface-variant': '#555555',
      '--color-surface': '#f3ede7',
      '--color-surface-dim': '#e7e0da',
      '--color-surface-bright': '#fbf5ef',
      '--color-surface-container': '#efe8e2',
      '--color-surface-container-high': '#e7e0da',
      '--color-surface-container-highest': '#dfd8d2',
      '--color-surface-container-low': '#f7f0ea',
      '--color-surface-container-lowest': '#ffffff',
      '--color-background': '#f5f0eb',
      '--color-outline': '#8a8a8a',
      '--color-outline-variant': '#c5c0ba',
      '--color-primary': '#381fd1',
      '--color-on-primary': '#ffffff',
      '--color-primary-container': '#381fd1',
      '--color-on-primary-container': '#ffffff',
      '--color-secondary': '#1c1b1b',
      '--color-on-secondary': '#ffffff',
      '--color-secondary-container': '#dfd8d2',
      '--color-on-secondary-container': '#1c1b1b',
      '--color-error': '#ba1a1a',
      '--color-on-error': '#ffffff',
      '--color-error-container': '#ffdad6',
      '--color-on-error-container': '#410002',
      '--color-inverse-surface': '#1c1b1b',
      '--color-inverse-on-surface': '#f3ede7',
      '--color-inverse-primary': '#381fd1',
      '--color-surface-tint': '#381fd1',
      '--color-primary-fixed': '#381fd1',
      '--color-primary-fixed-dim': '#2a15a8',
      '--color-on-primary-fixed': '#ffffff',
      '--color-on-primary-fixed-variant': '#ffffff',
      '--color-secondary-fixed': '#1c1b1b',
      '--color-secondary-fixed-dim': '#3a3a3a',
      '--color-on-secondary-fixed': '#ffffff',
      '--color-on-secondary-fixed-variant': '#ffffff',
      '--color-tertiary': '#1c1b1b',
      '--color-tertiary-container': '#dfd8d2',
      '--color-on-tertiary': '#ffffff',
      '--color-on-tertiary-container': '#1c1b1b',
      '--color-tertiary-fixed': '#1c1b1b',
      '--color-tertiary-fixed-dim': '#3a3a3a',
      '--color-on-tertiary-fixed': '#ffffff',
      '--color-on-tertiary-fixed-variant': '#ffffff',
      '--color-surface-variant': '#e7e0da',
    },
  },
}

function applyThemeStyles(customTheme: string | null, mode: 'dark' | 'light') {
  const palette = customTheme && customTheme !== 'none' && THEME_PALETTES[customTheme]
    ? THEME_PALETTES[customTheme]
    : DEFAULT_PALETTE
  const vars = palette[mode]
  for (const [key, value] of Object.entries(vars)) {
    document.documentElement.style.setProperty(key, value)
  }
}

interface ThemeState {
  customTheme: string
  themeMode: 'dark' | 'light'
  setCustomTheme: (id: string) => void
  setThemeMode: (mode: 'dark' | 'light') => void
  resetToDefault: () => void
}

export function applyCustomTheme(themeId: string | null, mode?: 'dark' | 'light') {
  const effectiveMode = mode || 'dark'

  // Set all color variables as inline styles (highest specificity — bypasses CSS cascade)
  applyThemeStyles(themeId, effectiveMode)

  // Also set CSS attribute selectors as secondary fallback
  if (themeId && themeId !== 'none') {
    document.documentElement.setAttribute('data-custom-theme', themeId)
  } else {
    document.documentElement.removeAttribute('data-custom-theme')
  }
  document.documentElement.setAttribute('data-theme-mode', effectiveMode)
}

/** Load theme preferences from the user's profile settings (Supabase). */
export async function loadThemeFromProfile(): Promise<{ customTheme: string; themeMode: 'dark' | 'light' } | null> {
  try {
    const result = await window.electronAPI?.getProfileSettings()
    const settings = result?.data || {}
    const customTheme = typeof settings.customTheme === 'string' ? settings.customTheme : null
    const themeMode = settings.themeMode === 'light' || settings.themeMode === 'dark' ? settings.themeMode : null
    if (customTheme !== null || themeMode !== null) {
      return { customTheme: customTheme || 'none', themeMode: themeMode || 'dark' }
    }
  } catch {}
  return null
}

/** Save theme preferences to the user's profile settings (Supabase). */
async function saveThemeToProfile(customTheme: string, themeMode: string) {
  try {
    await window.electronAPI?.mergeProfileSettings({ customTheme, themeMode })
  } catch {}
}

export const useThemeStore = create<ThemeState>((set) => ({
  customTheme: 'none',
  themeMode: 'dark',
  setCustomTheme: (id) => {
    const state = useThemeStore.getState()
    // Obscura is a stark monochrome theme — always force dark mode
    const desiredMode = id === 'unseen-studio' ? 'dark' : state.themeMode

    set({ customTheme: id, themeMode: desiredMode })
    saveThemeToProfile(id, desiredMode)
    applyCustomTheme(id === 'none' ? null : id, desiredMode)
  },
  setThemeMode: (mode) => {
    set({ themeMode: mode })
    const state = useThemeStore.getState()
    saveThemeToProfile(state.customTheme, mode)
    applyCustomTheme(state.customTheme === 'none' ? null : state.customTheme, mode)
  },
  resetToDefault: () => {
    set({ customTheme: 'none', themeMode: 'dark' })
    applyCustomTheme(null, 'dark')
  },
}))
